// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'contacts.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Contacts _$ContactsFromJson(Map<String, dynamic> json) => Contacts(
      id: (json['id'] as num).toInt(),
      firstName: json['first_name'] as String?,
      lastName: json['last_name'] as String?,
      dateOfBirth: json['date_of_birth'] as String?,
      countryOfBirth: json['country_of_birth'] as String?,
      estimatedAge: json['estimated_age'] as String?,
      gender: json['gender'] as String?,
      status: json['status'] as bool?,
      nationality: json['nationality'] as String?,
      nationalId: json['national_id'] as String?,
      nidPhotoOne: json['nid_photo_one'] as String?,
      nidPhotoTwo: json['nid_photo_two'] as String?,
      haveMedicalInsurance: json['have_medical_insurance'] as bool?,
      noOfChildren: (json['no_of_children'] as num?)?.toInt(),
      medicalInsuranceName: json['medical_insurance_name'] as String?,
      medicalInsuranceId: json['medical_insurance_id'] as String?,
      midPhotoOne: json['mid_photo_one'] as String?,
      midPhotoTwo: json['mid_photo_two'] as String?,
      ethnicity: json['ethnicity'] as String?,
      religion: json['religion'] as String?,
      occupation: json['occupation'] as String?,
      educationLevel: json['education_level'] as String?,
      meritalStatus: json['merital_status'] as String?,
      haveChildren: json['have_children'] as bool?,
      bloodGroup: json['blood_group'] as String?,
      email: json['email'] as String?,
      username: json['username'] as String?,
      phone: json['phone'] as String?,
      height: json['height'] as String?,
      weight: json['weight'] as String?,
      bmi: json['bmi'] as String?,
      alergies: json['alergies'] as String?,
      profilePhoto: json['profile_photo'] as String?,
      isFindable: json['is_findable'] as bool?,
      createdDate: json['created_date'] as String?,
      createdUid: (json['created_uid'] as num?)?.toInt(),
      updatedDate: json['updated_date'] as String?,
      updatedUid: (json['updated_uid'] as num?)?.toInt(),
      createdBy: json['created_by'] as String?,
      updatedBy: json['updated_by'] as String?,
    );

Map<String, dynamic> _$ContactsToJson(Contacts instance) => <String, dynamic>{
      'id': instance.id,
      'first_name': instance.firstName,
      'last_name': instance.lastName,
      'date_of_birth': instance.dateOfBirth,
      'country_of_birth': instance.countryOfBirth,
      'estimated_age': instance.estimatedAge,
      'gender': instance.gender,
      'status': instance.status,
      'nationality': instance.nationality,
      'national_id': instance.nationalId,
      'nid_photo_one': instance.nidPhotoOne,
      'nid_photo_two': instance.nidPhotoTwo,
      'have_medical_insurance': instance.haveMedicalInsurance,
      'no_of_children': instance.noOfChildren,
      'medical_insurance_name': instance.medicalInsuranceName,
      'medical_insurance_id': instance.medicalInsuranceId,
      'mid_photo_one': instance.midPhotoOne,
      'mid_photo_two': instance.midPhotoTwo,
      'ethnicity': instance.ethnicity,
      'religion': instance.religion,
      'occupation': instance.occupation,
      'education_level': instance.educationLevel,
      'merital_status': instance.meritalStatus,
      'have_children': instance.haveChildren,
      'blood_group': instance.bloodGroup,
      'email': instance.email,
      'username': instance.username,
      'phone': instance.phone,
      'height': instance.height,
      'weight': instance.weight,
      'bmi': instance.bmi,
      'alergies': instance.alergies,
      'profile_photo': instance.profilePhoto,
      'is_findable': instance.isFindable,
      'created_date': instance.createdDate,
      'created_uid': instance.createdUid,
      'created_by': instance.createdBy,
      'updated_by': instance.updatedBy,
      'updated_date': instance.updatedDate,
      'updated_uid': instance.updatedUid,
    };
